### PR TITLE
Feature/js quiz

### PR DESCRIPTION
**Pull request by cxs1mon**

### CODE REVIEW

**Comment by cxs1mon** [comment]
Transformed code into a component

**Comment by tomasbeloch** [comment]
@cxs1mon convert `decodeCorrectAnswer` and `decodeAnswerText` to a function.

**Comment by tomasbeloch** [comment]
@cxs1mon styling of the component is missing, you need to add <style> where you set the template.

**Comment by cxs1mon** [comment]
added style tag to the template

**Comment by cxs1mon** [comment]
> convert `decodeCorrectAnswer` and `decodeAnswerText` to a function.

done

**Pull request merged**
